# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 05:04
from __future__ import unicode_literals

from areas.models import Area as AreaModel
from django.conf import settings
from django.db import migrations, models
from django.template.defaultfilters import slugify
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import localflavor.us.models


def populate_areas(apps, schema_editor):
    Area = apps.get_model('areas', 'Area')
    for k,v in AreaModel.AREA_MAPS.iteritems():
        Area.objects.create(name=k, slug=slugify(k), color=v['color'])



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaPrecinct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=12, null=True)),
                ('long_name', models.CharField(blank=True, max_length=100)),
                ('author_provided_id', models.CharField(blank=True, max_length=60, null=True)),
                ('sq_miles', models.FloatField(blank=True, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('county_fips_code', models.CharField(blank=True, max_length=60, null=True)),
                ('map_cache_geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Washington Precinct',
                'db_table': 'wa_precincts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Precinct Area',
            },
        ),
        migrations.RunPython(populate_areas, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='PrecinctCoordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', localflavor.us.models.PhoneNumberField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, choices=[(None, 'Other / No Data'), ('elected', 'Elected PCO, pre-reorg'), ('appointed', 'Appointed PCO, pre-reorg'), ('acting', 'Acting PCO, pre-reorg'), ('elected-post-reorg', 'Elected PCO, post-reorg'), ('volunteer', 'Volunteer')], default=None, max_length=32, null=True)),
                ('status', models.CharField(blank=True, choices=[(None, 'No data'), ('will-walk', 'Will Walk'), ('picked-up-packet', 'Has Packet'), ('walked', 'Walked'), ('data-entered', 'Data Entered'), ('will-not-walk', 'Will Not Walk')], default=None, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
                ('precinct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.WaPrecinct')),
            ],
        ),
    ]
