# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models
from areas.models import AFFILIATIONS



def create_affiliations(apps, schema_editor):
    Affiliation = apps.get_model('areas', 'Affiliation')
    PrecinctCoordinator = apps.get_model('areas', 'PrecinctCoordinator')

    AffilationsThroughModel = PrecinctCoordinator.affiliations.through

    for key, value in AFFILIATIONS:
        if not key:
            continue

        affiliation = Affiliation.objects.create(label=value, slug=key)

        affiliations_to_create = []
        for coordinator in PrecinctCoordinator.objects.filter(affiliation=key):
            affiliations_to_create.append(AffilationsThroughModel(precinctcoordinator_id=coordinator.id, affiliation_id=affiliation.id))

        AffilationsThroughModel.objects.bulk_create(affiliations_to_create)



class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_precinctcoordinator_mini_van'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='precinctcoordinator',
            name='affiliations',
            field=models.ManyToManyField(blank=True, to='areas.Affiliation'),
        ),
        migrations.RunPython(create_affiliations, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='precinctcoordinator',
            options={'ordering': ('precinct__long_name', 'status', 'full_name')},
        ),
        migrations.AlterField(
            model_name='precinctcoordinator',
            name='mini_van',
            field=models.BooleanField(default=False, verbose_name='MiniVAN'),
        ),
        migrations.RemoveField(
            model_name='precinctcoordinator',
            name='affiliation',
        ),
    ]
