# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20161007_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precinctcoordinator',
            name='status',
            field=models.CharField(blank=True, choices=[(None, '-'), ('email', 'Email'), ('voicemail', 'Voicemail'), ('will-walk', 'Will Walk'), ('picked-up-packet', 'Has Packet'), ('walked', 'Walked'), ('data-entered', 'Data Entered'), ('will-not-walk', 'Will Not Walk')], default=None, max_length=32, null=True),
        ),
    ]
